hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
service:
  hosts:
    greeting: localhost:9090
    name: localhost:7070
---
spring:
  profiles: docker
service:
  hosts:
    greeting: greeting-service:9090
    name: name-service:7070
